export const languages = [
  { code: "en", name: "English", dir: "ltr" },
  { code: "ar", name: "العربية", dir: "rtl" },
  { code: "fr", name: "Français", dir: "ltr" },
  { code: "es", name: "Español", dir: "ltr" },
  { code: "de", name: "Deutsch", dir: "ltr" },
  { code: "it", name: "Italiano", dir: "ltr" },
  { code: "pt", name: "Português", dir: "ltr" },
  { code: "ru", name: "Русский", dir: "ltr" },
  { code: "zh", name: "中文", dir: "ltr" },
  { code: "ja", name: "日本語", dir: "ltr" },
  { code: "ko", name: "한국어", dir: "ltr" },
  { code: "tr", name: "Türkçe", dir: "ltr" },
  { code: "hi", name: "हिन्दी", dir: "ltr" },
  { code: "ur", name: "اردو", dir: "rtl" },
  { code: "fa", name: "فارسی", dir: "rtl" },
  { code: "he", name: "עברית", dir: "rtl" },
  { code: "id", name: "Bahasa Indonesia", dir: "ltr" },
  { code: "ms", name: "Bahasa Melayu", dir: "ltr" },
  { code: "th", name: "ไทย", dir: "ltr" },
  { code: "vi", name: "Tiếng Việt", dir: "ltr" },
  { code: "nl", name: "Nederlands", dir: "ltr" },
  { code: "pl", name: "Polski", dir: "ltr" },
  { code: "sv", name: "Svenska", dir: "ltr" },
  { code: "no", name: "Norsk", dir: "ltr" },
  { code: "da", name: "Dansk", dir: "ltr" },
  { code: "fi", name: "Suomi", dir: "ltr" },
  { code: "el", name: "Ελληνικά", dir: "ltr" },
  { code: "ro", name: "Română", dir: "ltr" },
  { code: "uk", name: "Українська", dir: "ltr" },
  { code: "bn", name: "বাংলা", dir: "ltr" },
  { code: "sw", name: "Kiswahili", dir: "ltr" },
];